# coding: utf-8
#
# unobtainium-cucumber
# https://github.com/jfinkhaeuser/unobtainium-cucumber
#
# Copyright (c) 2016 Jens Finkhaeuser and other unobtainium-cucumber
# contributors. All rights reserved.
#

driver: headless

# The following configuration options may be used to change the behaviour of
# the test suite.
#
# cucumber:
#   driver_reset: false
