# coding: utf-8
#
# unobtainium-cucumber
# https://github.com/jfinkhaeuser/unobtainium-cucumber
#
# Copyright (c) 2016 Jens Finkhaeuser and other unobtainium-cucumber
# contributors. All rights reserved.
#

driver: headless

cucumber:

# The following configuration options may be used to change the behaviour of
# the test suite.
#
#   driver_reset: false

# The following options are expected by the test suite. Changing them may
# make the test suite fail. Proceed with caution!
  status_actions:
    passed?:
      - global_action
    failed?:
      outline:
        - dummy_action
      scenario:
        - method_from_own_extension
